server:
  port: ${USER_PORT}

spring:
  application:
    name: user
  datasource:
    url: ${DB_DATABASE}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: ${DRIVER_CLASS}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: ${DDL}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        highlight_sql: true
  data:
    redis:
      host: ${REDIS_DOMAIN}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}


eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_DOMAIN}:${EUREKA_PORT}/eureka/

# swagger 사용시 패키지 이름까지 사용해서 구별하도록 설정
springdoc:
  use-fqn: true

# 로그 수준
logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace

jwt:
  secret:
    key: ${JWT_SECRET_KEY}
  refresh:
    secret:
      key: ${JWT_REFRESH_SECRET_KEY}

slack:
  bot:
    token: ${SLACK_BOT_TOKEN}
  channel:
    id: ${SLACK_CHANNEL_ID}