server:
  port: ${USER_PORT}

spring:
  application:
    name: user

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_DOMAIN}:${EUREKA_PORT}/eureka/

# swagger 사용시 패키지 이름까지 사용해서 구별하도록 설정
springdoc:
  use-fqn: true

# 로그 수준
logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace