server:
  port: ${ORDER_PORT}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_DOMAIN}:${EUREKA_PORT}/eureka/

spring:
  datasource:
    url: ${DB_DATABASE}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: ${DRIVER_CLASS}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: ${DDL}
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true

