server:
  port: ${HUB_PRODUCT_PORT}

spring:
  cloud:
    config:
      enabled: false  # Config 서버 사용 안함
  application:
    name: user
  datasource:
    url: ${DB_DATABASE}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: ${DRIVER_CLASS}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: ${DDL}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        highlight_sql: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_DOMAIN}:${EUREKA_PORT}/eureka/

# swagger 사용시 패키지 이름까지 사용해서 구별하도록 설정
springdoc:
  use-fqn: true

# 로그 수준
logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace
